version: '3.8'

services:

  mongo:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  node:
    container_name: node
    build:
      context: .
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - mern-network

  react:
    container_name: react
    build:
      context: ./client
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - node
    networks:
      - mern-network

volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge
